### ISSUE TITLE
Does this work with macOS / Apple Silicon?

### ISSUE THREAD

**Issue by bbatchelder** [tvandinther/libsql-client-dotnet#17]
I clone the repo, generate the bindings, build the demo...which all seems to work, but when I run the demo I get:

Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Demo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Similarly when I create a new project and add the Libsql.Client nuget package...the app builds fine but when run I get:

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Libsql.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Any ideas?

**Comment by tvandinther** [comment]
I have opened #18 to address "issue 2" outlined above and will keep this issue open for "issue 1".

**Comment by tvandinther** [comment]
Nice, I'm glad that did it. I will consider updating the configuration to unrestrict the platform target and close this issue once I decide whether or not to make the change.

**Comment by tvandinther** [comment]
I will remove the platform target to for the implied `AnyCPU` default.
