### ISSUE TITLE
IDatabaseClient should implement IDisposable

### ISSUE THREAD

**Issue by jiri-matejka** [tvandinther/libsql-client-dotnet#29]
Interface IDatabaseClient should implement IDisposable because its implementation, DatabaseWrapper, is disposable:

```csharp
internal class DatabaseWrapper : IDatabaseClient, IDisposable
```

Currently I cannot use `using` statement since IDatabaseClient returned from `await DatabaseClient.Create(...)` is not disposable.

The only thing what I can do is
```csharp
var dbClient = await DatabaseClient.Create();
try
{
   await dbClient.Execute(...);
}
finally
{
  ((IDisposable)dbClient).Dispose();
}
```

**Comment by tvandinther** [comment]
Fixed in #30
